global:
  checkNewVersion: true
  sendAnonymousUsage: true

accessLog: {}

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  # standard port 80 entry 
  # redirect everything from WEB to WEBSECURE
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    forwardedHeaders:
      # Start of Clouflare public IP list for HTTP requests, remove this if you don't use


  # HTTPS entry, with domain wild card
  websecure:
    address: :443
    http:
      tls:
        #certResolver: cloudflare
        domains:
          - main: example.com
            sans:
              - '*.example.com'
      middlewares:
        - securityHeaders@file

certificatesResolvers:
  cloudflare:
    acme:
      email: "your-email"
      storage: /etc/traefik/certs/cloudflare-acme.json
      #caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    network: proxy
    # Create some default rules
    #defaultRule: "Host(`{{ lower( .Name )}}.example.com`)"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.example.com`)"
  file:
    directory: /etc/traefik/conf/
    watch: true